### ISSUE TITLE
Failed to query fields of type Decimal and data is 0

### ISSUE THREAD

**Issue by eye-gu** [housepower/spark-clickhouse-connector#265]
spark sql: select number_col1 from `clickhouse`.`zhouwq`.`user_test`;

![image](https://github.com/housepower/spark-clickhouse-connector/assets/20450037/29046ab2-a2a6-410a-aebf-50b9df0d29c4)

## log 

spark-sql> select number_col1 from `clickhouse`.`zhouwq`.`user_test`;
23/08/10 18:11:38 ERROR Executor: Exception in task 1.0 in stage 0.0 (TID 1)
java.lang.NullPointerException
	at java.math.BigDecimal.<init>(BigDecimal.java:831)
	at scala.math.BigDecimal$.apply(BigDecimal.scala:290)
	at xenon.clickhouse.read.format.ClickHouseJsonReader.decodeValue(ClickHouseJsonReader.scala:74)
	at xenon.clickhouse.read.format.ClickHouseJsonReader.decode(ClickHouseJsonReader.scala:48)
	at xenon.clickhouse.read.format.ClickHouseJsonReader.decode(ClickHouseJsonReader.scala:33)
	at xenon.clickhouse.read.ClickHouseReader.get(ClickHouseReader.scala:89)
	at xenon.clickhouse.read.ClickHouseReader.get(ClickHouseReader.scala:29)

**Comment by eye-gu** [comment]
![image](https://github.com/housepower/spark-clickhouse-connector/assets/20450037/2172ca00-0c82-433d-a876-1281d4143cab)

maybe use `asText` method is better

**Comment by pan3793** [comment]
I think `asText` does not help, if ClickHouse eliminates data of 0 in result, we should set it to default value explicitly.
```
scala> BigDecimal("")
java.lang.NumberFormatException
  at java.math.BigDecimal.<init>(BigDecimal.java:599)
  at java.math.BigDecimal.<init>(BigDecimal.java:383)
  at java.math.BigDecimal.<init>(BigDecimal.java:809)
  at scala.math.BigDecimal$.exact(BigDecimal.scala:126)
  at scala.math.BigDecimal$.apply(BigDecimal.scala:284)
  ... 47 elided
```

**Comment by pan3793** [comment]
BTW, thanks for reporting this issue, PR is welcome~

**Comment by eye-gu** [comment]
I'm not sure what caused it. In my local environment, it works after modifying to 'asText'

**Comment by pan3793** [comment]
Could you try this way?

```patch
      case d: DecimalType if jsonNode.isBigDecimal =>
        Decimal(jsonNode.decimalValue, d.precision, d.scale)
      case d: DecimalType if jsonNode.isFloat | jsonNode.isDouble =>
        Decimal(BigDecimal(jsonNode.doubleValue, new MathContext(d.precision)), d.precision, d.scale)
+     case d: DecimalType if jsonNode.inInt =>
+       Decimal(BigDecimal(jsonNode.intValue, new MathContext(d.precision)), d.precision, d.scale)
      case d: DecimalType =>
        Decimal(BigDecimal(jsonNode.textValue, new MathContext(d.precision)), d.precision, d.scale)
```

**Comment by pan3793** [comment]
Seems there are other unhandled cases here, like isLong, isBigInteger ...

**Comment by eye-gu** [comment]
`isInt` works

**Comment by pan3793** [comment]
So that's the root cause, would like to send PR to fix it, and other potential cases?

**Comment by eye-gu** [comment]
PTAL

**Comment by eye-gu** [comment]
I found that the `binary` format does not have this issue, also #264 issue. Is it more recommended to use `binary`?

**Comment by paf91** [comment]
issue is still present. any updates?

**Comment by paf91** [comment]
![image](https://github.com/housepower/spark-clickhouse-connector/assets/12195041/0cbd6ca1-53ec-4bc4-a505-b92055099f21)

**Comment by pan3793** [comment]
@paf91 I need to find some time to publish a new version containing this patch, maybe in a few days, you can try building the master branch before the publish is done.

**Comment by pan3793** [comment]
@paf91 FYI, 0.7.3 is available now, it includes this patch.

**Comment by pan3793** [comment]
@paf91 Well, the "best practices" depend on a lot of stuff. The built-in JDBC data source is maintained by the Apache Spark community as a general solution for interacting with RDBMS, just keep using it if it works well for your cases.

Instead of providing best practices, I'd like to list some points that I think are worth careful consideration.

Performance in the distributed system is a big topic, I wrote an [article](https://housepower.github.io/spark-clickhouse-connector/internals/03_write/) to explain how this connector improves the query performance.

Convenience. For example, the data engineer may want to use `CREATE/REPLACE TABLE ... AS SELECT ...` or equivalent `df.writeTo(table).create()` and `df.writeTo(table).createOrReplace()`, it's not possible without [SPARK-43390](https://github.com/apache/spark/pull/41070)

Transactions. For a long time, transactions were not strict or even missing in the big data world. In a distributed system, the failure of a single node is normal. Without the guarantee of writing transactions, the resulting retries may lead to eventual data duplication. Have some thoughts about this topic previously https://github.com/housepower/spark-clickhouse-connector/issues/145
