### ISSUE TITLE
Sources jar uploaded to Maven Central is empty

### ISSUE THREAD

**Issue by heartdance** [housepower/spark-clickhouse-connector#302]
发布到maven中央仓库的源码包没有内容，大小只有不到1kb

**Comment by pan3793** [comment]
link?

**Comment by heartdance** [comment]
> link?

[https://mvnrepository.com/artifact/com.github.housepower/clickhouse-spark-runtime-3.3_2.12/0.7.3](https://mvnrepository.com/artifact/com.github.housepower/clickhouse-spark-runtime-3.3_2.12/0.7.3)

我看了几个都没有，这只是其中之一

**Comment by pan3793** [comment]
It's by design.

The `*-runtime-*.jar` shippes relocated classes, technically, there is no corresponding source code, though Maven/Gradle shadow plugins support generating the modified source code jars, but it is almost a mess, a negative case is HADOOP-16822.

While docs and sources jars are enforced by sonatype[1], so dummy jars are used eventually.

[1] https://central.sonatype.org/publish/requirements/#publishing
